addons:
  apt:
    packages:
    - expect-dev
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
- '3.7-dev'
env:
  global:
  - PROJECT="Cannabis Reports"
  - DOCS_PY_VERSION="3.5"
  matrix:
  - TESTS="1"
  - DOCS="1"
  - LINT="1"
install:
- git clone --depth=1 https://github.com/LasLabs/python-quality-tools.git ${HOME}/python-quality-tools
- export PATH=${HOME}/python-quality-tools/travis:${PATH}
- travis_install
script:
- travis_run
after_success:
- travis_after_success
deploy:
  provider: pypi
  user: laslabs
  password:
    secure: d2p9xwrghL/SXRQmZLER2cmPjfgxoPMSan4FRmJYFfpvKpeG4o+7xEyfbDV3wN7mJvo4/hWcEdgK4CpwJxIGv2W7XD8bRBm3X/JGUACM+A6lKB1gyXg8ObVw3blZUR2rL+AEYrach7OBCrcFxCRfvnU5o5ApCLHC5jxj4DSRPABlMEJ6WcCkbm8PL+JroYxXF8pTkeuF9t0njEFb6mHWpDFUvk/t+Z3N15215PEA1Dg79G7TbteFmgLGRj9B/r/MDWPHFi7Kvrdkjo3OnGez573WXrgPQz/et/ztz4RgxCZOLAVTm9RrlLJJBCx8gRX6aQqAS7ZHDvquqZmiEwrnBzuIiVirf6H8jyQEgjf+2Ch6JeHftoAHNYTOvVCBO/ouHOD0wSsXA9ZA8juYame1vwjGMHV8J2S5A5gCTnsjjROx2xrjTo+sSeulRc+IHrv0jZi1rtBN+H3Kj9QGjnEMVLZ49CK3F+yYqc+c4LvAmttojk9ZTKNrtSc4bER9f9+l02RFrstfEFz7XfYuUrskfsRhNY81RnpquhHMlzoSIAwunBO4/beqtqkUvP8uwOWZXzT+aRypgh5HAfGhM5+SS9XkT+z3Ccl17OJrqijR4bM+kAKpM3ImNxUIfGBXGsYpMkUu2rJbsDBSj+y60ptO5xsNTJ08YB8TRwBYFa5kUiE=
  skip_cleanup: false
  skip_upload_docs: true
  on:
    repo: LasLabs/python-helpscout
    branch: master
    tags: true
